### ISSUE TITLE
Not a properly formatted package

### ISSUE THREAD

**Issue by MarcoPrins** [kurko/ember-json-api#87] opened 2015-07-01 11:58 UTC
This warning shows up when running `ember s`:
````
The package `ember-json-api` is not a properly formatted package, we have used 
a fallback lookup to resolve it at `/Users/marcoprins/Desktop/Project/ember_test/censored/node_modules/ember-json-api`.
This is generally caused by an addon not having a `main` entry point (or `index.js`).
````

And when I try to update , I get this error:

````
$ npm update ember-json-api
npm ERR! cb() never called!
````

Ember cli `v0.2.7`
Ember `v1.13.0`
Node.js `v0.10.35`

**Comment by jonkoops** [comment] 2015-07-01 14:08
@MarcoPrins What is the version of Ember JSON API you are running?

**Comment by MarcoPrins** [comment] 2015-07-01 14:11
@jonkoops Version 0.3.0

**Comment by jonkoops** [comment] 2015-07-01 16:08
@MarcoPrins The latest version (0.5.0) has a fix that should prevent the deprecation issues you are seeing.

As for the NPM error I think it is related to an NPM bug not a bug in Ember JSON API. Make sure you are using the latest version of Node.js (or IO.js) and update to the latest version of NPM (`npm install -g npm@latest`).

If you are still expeiencing issues please run the following commands from your project root:

`rm -rf node_modules/`
`npm cache clean`
`npm install`

If you are looking to update your project to work with the v1.0 of the JSON API specification you should probably migrate to the [offical Ember Data adapter](http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html).

**Comment by kurko** [comment] 2015-07-02 20:01
Thanks @jonkoops for the thorough instructions.

@MarcoPrins please update to 0.5.0. I'm closing this for now. Please reopen if the problem persists on 0.5.0 :smile:

**Comment by MarcoPrins** [comment] 2015-07-03 07:24
Thanks for your helpful answer @jonkoops !
This is more due to npm not wanting to update than anything else.
`0.5.0` does remove the deprecation warning

**Comment by jonkoops** [comment] 2015-07-03 07:47
Okay. If this fixes your issue I am going ahead and close this.

**Closed by jonkoops** 2015-07-03 07:47 UTC
